


all:
# 	source ~/goinfre/global-env/bin/activate
	python3 app.py

in:
	source ~/goinfre/global-env/bin/activate 
	pip install -r requirements.txt

create:
	python3 -m venv ~/goinfre/global-env/bin/activate

seed:
	python3 seeding.py