import L from "leaflet";
import { School } from "./types";

export const schools: School[] = [
  {
    id: "ensias",
    name: "ENSIAS - National School of Computer Science",
    abrv: "ENSIAS",
    city: "Rabat",
    category: "Engineering",
    coordinates: [-6.8676, 33.9842],
    color: "bg-[#ccee00]",
    address: "Madinat Al Irfane, Rabat",
    years: 3,
  },
  {
    id: "inpt",
    name: "INPT - National Institute of Posts & Telecoms",
    abrv: "INPT",
    city: "Rabat",
    category: "Engineering",
    coordinates: [-6.858, 33.978],
    color: "bg-[#9bf6ff]",
    address: "Allal Al Fassi, Rabat",
    years: 3,
  },
  {
    id: "emi",
    name: "EMI - Mohammadia School of Engineers",
    abrv: "EMI",
    city: "Rabat",
    category: "Engineering",
    coordinates: [-6.848, 34.002],
    color: "bg-[#ffd6a5]",
    address: "Agdal, Rabat",
    years: 3,
  },
  {
    id: "um5",
    name: "Mohammed V University",
    abrv: "UM5",
    city: "Rabat",
    category: "University",
    coordinates: [-6.8361, 34.0084],
    color: "bg-[#ffb3c6]",
    address: "Agdal, Rabat",
    years: 5,
  },
  {
    id: "ehtp",
    name: "EHTP - Hassania School of Public Works",
    abrv: "EHTP",
    city: "Casablanca",
    category: "Engineering",
    coordinates: [-7.6534, 33.5467],
    color: "bg-[#9bf6ff]",
    address: "Km 7 Route d'El Jadida, Casablanca",
    years: 3,
  },
  {
    id: "encg-casa",
    name: "ENCG Casablanca - Business School",
    abrv: "ENCG",
    city: "Casablanca",
    category: "Business",
    coordinates: [-7.632, 33.589],
    color: "bg-[#0ea5e9]",
    address: "Beau Sejour, Casablanca",
    years: 5,
  },
  {
    id: "est-casa",
    name: "EST Casablanca - High School of Technology",
    abrv: "EST",
    city: "Casablanca",
    category: "Technology",
    coordinates: [-7.615, 33.555],
    color: "bg-[#ccee00]",
    address: "Route d'El Jadida, Casablanca",
    years: 2,
  },
  {
    id: "ensam-meknes",
    name: "ENSAM Meknes - Arts & Metiers",
    abrv: "ENSAM",
    city: "Meknes",
    category: "Engineering",
    coordinates: [-5.539, 33.869],
    color: "bg-[#ffd6a5]",
    address: "Marjane II, Meknes",
    years: 5,
  },
  {
    id: "est-meknes",
    name: "EST Meknes - Technology Institute",
    abrv: "EST",
    city: "Meknes",
    category: "Technology",
    coordinates: [-5.545, 33.881],
    color: "bg-[#ffb3c6]",
    address: "Km 5 Route d'Agourai, Meknes",
    years: 2,
  },
  {
    id: "fst-fes",
    name: "FST Fes - Faculty of Sciences & Technology",
    abrv: "FST",
    city: "Fes",
    category: "Sciences",
    coordinates: [-4.992, 34.033],
    color: "bg-[#9bf6ff]",
    address: "Route d'Imouzzer, Fes",
    years: 3,
  },
  {
    id: "fst-kech",
    name: "FST Marrakech - Sciences & Tech",
    abrv: "FST",
    city: "Marrakech",
    category: "Sciences",
    coordinates: [-8.021, 31.642],
    color: "bg-[#ccee00]",
    address: "Bd Abdelkarim Al Khattabi, Marrakech",
    years: 3,
  },
  {
    id: "encg-kech",
    name: "ENCG Marrakech - Management",
    abrv: "ENCG",
    city: "Marrakech",
    category: "Business",
    coordinates: [-8.015, 31.635],
    color: "bg-[#0ea5e9]",
    address: "Amerchich, Marrakech",
    years: 5,
  },
  {
    id: "ensa-tangier",
    name: "ENSA Tangier - Applied Sciences",
    abrv: "ENSA",
    city: "Tangier",
    category: "Engineering",
    coordinates: [-5.892, 35.738],
    color: "bg-[#ffd6a5]",
    address: "Ziaten, Tangier",
    years: 5,
  },
  {
    id: "encg-settat",
    name: "ENCG Settat - Management & Commerce",
    abrv: "ENCG",
    city: "Settat",
    category: "Business",
    coordinates: [-7.6186, 33.0017],
    color: "bg-[#ffb3c6]",
    address: "Km 3 Route de Casablanca, Settat",
    years: 5,
  },
  {
    id: "fst-settat",
    name: "FST Settat - Sciences & Tech",
    abrv: "FST",
    city: "Settat",
    category: "Sciences",
    coordinates: [-7.622, 33.01],
    color: "bg-[#9bf6ff]",
    address: "Km 3 Route de Casablanca, Settat",
    years: 3,
  },
];

export const MOROCCO_BOUNDS_LEAFLET: L.LatLngBoundsExpression = [
  [20.5, -17.5],
  [36.4, -0.8],
];

export const DEFAULT_CENTER: L.LatLngExpression = [29.2, -9.0];
